In [201]:
import pandas as pd

In [202]:
dataset=pd.read_csv("RetailDataset.csv")
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32
2,NaN,Electronics,Cust_205,UK,22-10-2024,8,1470,0.22,1040.0,9172.80
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48
...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00

In [203]:
dataset.head(5)

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32
2,NaN,Electronics,Cust_205,UK,22-10-2024,8,1470,0.22,1040.0,9172.80
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48

In [204]:
dataset.tail(5)

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00

In [205]:
dataset.describe(include='all')

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
count,4904,5000,5000,5000,5000,5000.000000,5000.000000,4900.000000,4898.000000,5000.000000
unique,8,3,500,6,1085,NaN,NaN,NaN,NaN,NaN
top,Printer,Accessories,Cust_480,Germany,27-01-2023,NaN,NaN,NaN,NaN,NaN
freq,644,1692,19,878,15,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,4.954800,1025.086200,0.151865,769.012046,4735.041952
std,NaN,NaN,NaN,NaN,NaN,2.554068,560.293526,0.086790,425.539933,6456.650648
min,NaN,NaN,NaN,NaN,NaN,1.000000,50.000000,0.000000,30.000000,40.470000
25%,NaN,NaN,NaN,NaN,NaN,3.000000,535.000000,0.080000,395.250000,1460.025000
50%,NaN,NaN,NaN,NaN,NaN,5.000000,1014.000000,0.150000,774.500000,3406.040000
75%,NaN,NaN,NaN,NaN,NaN,7.000000,1510.250000,0.230000,1132.750000,6553.980000
max,NaN,NaN,NaN,NaN,NaN,9.000000,1999.000000,0.300000,1499.000000,162604.800000

In [206]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Product     4904 non-null   object
 1   Category    5000 non-null   object
 2   Customer    5000 non-null   object
 3   Region      5000 non-null   object
 4   Date        5000 non-null   object
 5   Quantity    5000 non-null   int64
 6   Unit Price  5000 non-null   int64
 7   Discount    4900 non-null   float64
 8   Cost        4898 non-null   float64
 9   Sales       5000 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 390.8+ KB

In [207]:
dataset.shape

(5000, 10)

In [208]:
dataset.columns

Index(['Product', 'Category', 'Customer', 'Region', 'Date', 'Quantity',
       'Unit Price', 'Discount', 'Cost', 'Sales'],
      dtype='object')

In [209]:
dataset.dtypes

Product        object
Category       object
Customer       object
Region         object
Date           object
Quantity        int64
Unit Price      int64
Discount      float64
Cost          float64
Sales         float64
dtype: object

In [210]:
dataset.columns=dataset.columns.str.strip()
dataset.columns

Index(['Product', 'Category', 'Customer', 'Region', 'Date', 'Quantity',
       'Unit Price', 'Discount', 'Cost', 'Sales'],
      dtype='object')

In [211]:
dataset.isnull().sum()

Product        96
Category        0
Customer        0
Region          0
Date            0
Quantity        0
Unit Price      0
Discount      100
Cost          102
Sales           0
dtype: int64

In [212]:
dataset.dropna(subset=['Product','Cost'], inplace=True)

In [213]:
dataset['Discount']=dataset['Discount'].fillna(0)
dataset['Discount']

0       0.17
1       0.29
3       0.08
4       0.01
5       0.25
        ...
4995    0.08
4996    0.13
4997    0.21
4998    0.17
4999    0.17
Name: Discount, Length: 4803, dtype: float64

In [214]:
dataset.isnull().sum()

Product       0
Category      0
Customer      0
Region        0
Date          0
Quantity      0
Unit Price    0
Discount      0
Cost          0
Sales         0
dtype: int64

In [215]:
dataset.duplicated().sum()

np.int64(90)

In [216]:
# it actually shows the duplicate values
dataset[dataset.duplicated()]

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
478,Headphones,Electronics,Cust_232,Canada,30-10-2024,3,1578,0.09,118.0,4307.94
612,Keyboard,Office,Cust_9,Australia,09-01-2023,8,1679,0.05,1038.0,12760.40
843,Mouse,Office,Cust_393,Canada,03-01-2024,9,926,0.12,412.0,7333.92
927,Printer,Electronics,Cust_140,Australia,31-05-2023,6,823,0.30,1230.0,3456.60
986,Keyboard,Electronics,Cust_366,UK,24-07-2023,3,365,0.27,330.0,799.35
...,...,...,...,...,...,...,...,...,...,...
4890,Headphones,Office,Cust_452,India,09-04-2023,4,301,0.13,1455.0,1047.48
4896,Printer,Accessories,Cust_395,UK,14-07-2024,4,440,0.28,1365.0,1267.20
4925,Tablet,Electronics,Cust_249,India,05-12-2022,8,864,0.08,458.0,6359.04
4935,Keyboard,Office,Cust_287,Canada,26-12-2024,7,943,0.04,454.0,6336.96
4985,Headphones,Office,Cust_154,Germany,19-01-2022,1,1518,0.07,1188.0,1411.74

In [217]:
dataset.drop_duplicates(inplace=True)

In [218]:
dataset.shape

(4713, 10)

In [219]:
clean=dataset.rename(columns={'Cost':'Produ_Cost'})
clean
# Reminder dictionary

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75
...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00

In [220]:
dataset.sort_values('Sales',ascending=False)

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
858,Monitor,Accessories,Cust_474,Germany,12-01-2022,9,1882,0.04,761.0,162604.80
4003,Laptop,Electronics,Cust_53,USA,15-03-2022,7,1935,0.14,1268.0,116487.00
3885,Mouse,Office,Cust_416,India,07-04-2024,7,1696,0.02,694.0,116345.60
4320,Tablet,Electronics,Cust_329,UK,25-06-2022,7,1774,0.00,950.0,115487.40
3610,Monitor,Accessories,Cust_232,USA,09-07-2024,9,1217,0.07,497.0,101862.90
...,...,...,...,...,...,...,...,...,...,...
1157,Printer,Office,Cust_402,UK,29-11-2024,1,70,0.08,267.0,64.40
1125,Headphones,Accessories,Cust_173,Australia,27-06-2023,1,67,0.08,830.0,61.64
48,Mouse,Electronics,Cust_369,UK,25-05-2023,1,54,0.08,235.0,49.68
3028,Phone,Office,Cust_456,Canada,28-03-2022,1,67,0.28,1259.0,48.24
2441,Phone,Accessories,Cust_93,Australia,20-01-2022,1,57,0.29,1244.0,40.47

In [221]:
dataset['Customer'].value_counts()

Customer
Cust_281    18
Cust_271    17
Cust_235    17
Cust_480    17
Cust_77     16
            ..
Cust_124     4
Cust_117     3
Cust_97      3
Cust_36      3
Cust_14      2
Name: count, Length: 500, dtype: int64

In [222]:
dataset['Region'].unique()

array(['Canada', 'UK', 'USA', 'Germany', 'Australia', 'India'],
      dtype=object)

In [223]:
dataset['Region'].nunique()

6

In [224]:
dataset.query('Sales>100000')

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
858,Monitor,Accessories,Cust_474,Germany,12-01-2022,9,1882,0.04,761.0,162604.8
3610,Monitor,Accessories,Cust_232,USA,09-07-2024,9,1217,0.07,497.0,101862.9
3885,Mouse,Office,Cust_416,India,07-04-2024,7,1696,0.02,694.0,116345.6
4003,Laptop,Electronics,Cust_53,USA,15-03-2022,7,1935,0.14,1268.0,116487.0
4320,Tablet,Electronics,Cust_329,UK,25-06-2022,7,1774,0.00,950.0,115487.4

In [225]:
pd.pivot_table(dataset,values='Sales',index='Region',aggfunc='sum')

                Sales
Region
Australia  3650380.00
Canada     3555734.70
Germany    4030712.96
India      3834840.28
UK         3547774.58
USA        3731854.71

In [226]:
dataset_clean = (
    dataset
   .query("Sales > 100000 and Region == 'UK'")
    .assign(Product=lambda x: x["Product"].str.upper())
    .sort_values("Sales", ascending=False)
)
dataset_clean

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
4320,TABLET,Electronics,Cust_329,UK,25-06-2022,7,1774,0.0,950.0,115487.4

In [227]:
data_Clean=dataset.assign (
    
    Profit=lambda x: x["Sales"] - x["Cost"]
)
data_Clean

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Profit
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75
...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00

In [228]:
dataset["Region_Avg_Sales"] = dataset.groupby("Region")["Sales"].transform("mean")
dataset["Region_Avg_Sales"]

0       4395.222126
1       4395.222126
3       4736.681682
4       4395.222126
5       4395.222126
           ...
4995    4395.222126
4996    4741.873837
4997    4644.249364
4998    4644.249364
4999    4736.681682
Name: Region_Avg_Sales, Length: 4713, dtype: float64

In [229]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126
...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682

In [230]:
dataset["Sales_Level"] = pd.qcut(dataset["Sales"], q=4,
                             labels=["Low","Medium","High","Very High"])
dataset["Sales_Level"]

0            High
1            High
3             Low
4             Low
5       Very High
          ...
4995         High
4996         High
4997         High
4998    Very High
4999         High
Name: Sales_Level, Length: 4713, dtype: category
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Very High']

In [231]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High

In [232]:
dataset[(dataset["Sales"] > 100000) & (dataset["Region"] == "India")]

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level
3885,Mouse,Office,Cust_416,India,07-04-2024,7,1696,0.02,694.0,116345.6,5059.156042,Very High

In [233]:
data_replace=dataset['Customer'].str.replace("Cust_","Customer")
data_replace

0       Customer440
1       Customer480
3       Customer336
4       Customer440
5       Customer138
           ...
4995    Customer336
4996    Customer420
4997    Customer265
4998     Customer84
4999     Customer51
Name: Customer, Length: 4713, dtype: object

In [234]:
avg_revenue = dataset.groupby("Product")["Sales"].agg(["mean","sum","max"])
print(avg_revenue)

                   mean         sum       max
Product
Headphones  4532.157053  2583329.52   58664.4
Keyboard    4640.283678  2737767.37   59392.0
Laptop      5037.781142  3088159.84  116487.0
Monitor     4832.701466  2967278.70  162604.8
Mouse       5114.606324  2838606.51  116345.6
Phone       4717.600565  2755078.73   76944.0
Printer     4332.108685  2668578.95   27936.0
Tablet      4750.433643  2712497.61  115487.4

In [235]:
dataset.loc[0]

Product                 Printer
Category            Electronics
Customer               Cust_440
Region                   Canada
Date                 18-03-2023
Quantity                      8
Unit Price                  733
Discount                   0.17
Cost                     1153.0
Sales                   4867.12
Region_Avg_Sales    4395.222126
Sales_Level                High
Name: 0, dtype: object

In [236]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High

In [237]:
dataset['Profit']=dataset["Sales"]- dataset["Cost"]
dataset['Profit']

0       3714.12
1       5175.32
3        231.40
4        206.48
5       8559.75
         ...
4995    4779.28
4996    4005.90
4997    4439.32
4998    6447.35
4999    5217.00
Name: Profit, Length: 4713, dtype: float64

In [238]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level,Profit
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High,3714.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High,5175.32
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low,231.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low,206.48
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High,8559.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High,4779.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High,4005.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High,4439.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High,6447.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High,5217.00

In [239]:
dataset["Profit_Margin"]=(dataset["Profit"]/dataset["Sales"])*100
dataset["Profit_Margin"]

0       76.310426
1       91.205995
3       23.506705
4       24.479537
5       93.114139
          ...
4995    98.313201
4996    92.645528
4997    87.693390
4998    93.084381
4999    82.704502
Name: Profit_Margin, Length: 4713, dtype: float64

In [240]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level,Profit,Profit_Margin
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High,3714.12,76.310426
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High,5175.32,91.205995
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low,231.40,23.506705
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low,206.48,24.479537
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High,8559.75,93.114139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High,4779.28,98.313201
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High,4005.90,92.645528
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High,4439.32,87.693390
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High,6447.35,93.084381
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High,5217.00,82.704502

In [241]:
dataset["Total_Discount"]=dataset["Quantity"]*dataset["Unit Price"]*dataset["Discount"]
dataset["Total_Discount"]

0        996.88
1       2317.68
3         85.60
4          8.52
5       3064.25
         ...
4995     422.72
4996     646.10
4997    1345.68
4998    1418.65
4999    1292.00
Name: Total_Discount, Length: 4713, dtype: float64

In [242]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level,Profit,Profit_Margin,Total_Discount
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High,3714.12,76.310426,996.88
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High,5175.32,91.205995,2317.68
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low,231.40,23.506705,85.60
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low,206.48,24.479537,8.52
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High,8559.75,93.114139,3064.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High,4779.28,98.313201,422.72
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High,4005.90,92.645528,646.10
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High,4439.32,87.693390,1345.68
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High,6447.35,93.084381,1418.65
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High,5217.00,82.704502,1292.00

In [243]:
# Total revenue and profit of the each Region
Region_wise=dataset.groupby("Region")[["Sales","Profit"]].sum()
Region_wise

                Sales      Profit
Region
Australia  3650380.00  3054088.00
Canada     3555734.70  2926495.70
Germany    4030712.96  3397016.96
India      3834840.28  3257565.28
UK         3547774.58  2980757.58
USA        3731854.71  3125402.71

In [244]:
high_margin = dataset[dataset['Profit_Margin'] > 20]
high_margin

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level,Profit,Profit_Margin,Total_Discount
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High,3714.12,76.310426,996.88
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High,5175.32,91.205995,2317.68
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low,231.40,23.506705,85.60
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low,206.48,24.479537,8.52
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High,8559.75,93.114139,3064.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High,4779.28,98.313201,422.72
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High,4005.90,92.645528,646.10
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High,4439.32,87.693390,1345.68
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High,6447.35,93.084381,1418.65
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High,5217.00,82.704502,1292.00

In [245]:
low_margin = dataset[dataset['Profit_Margin'] < 10]
low_margin

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level,Profit,Profit_Margin,Total_Discount
15,Tablet,Office,Cust_29,UK,14-09-2023,2,63,0.08,938.0,115.92,4736.681682,Low,-822.08,-709.178744,10.08
16,Laptop,Electronics,Cust_289,USA,11-03-2023,2,674,0.29,1463.0,957.08,4741.873837,Low,-505.92,-52.860785,390.92
18,Phone,Accessories,Cust_382,Australia,16-05-2022,7,178,0.01,1151.0,1233.54,4644.249364,Low,82.54,6.691311,12.46
30,Phone,Office,Cust_175,Canada,12-12-2022,3,157,0.24,539.0,357.96,4395.222126,Low,-181.04,-50.575483,113.04
48,Mouse,Electronics,Cust_369,UK,25-05-2023,1,54,0.08,235.0,49.68,4736.681682,Low,-185.32,-373.027375,4.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4960,Laptop,Office,Cust_10,Germany,22-08-2023,3,60,0.05,1022.0,171.00,4891.641942,Low,-851.00,-497.660819,9.00
4971,Laptop,Electronics,Cust_279,UK,23-10-2022,2,406,0.11,654.0,722.68,4736.681682,Low,68.68,9.503515,89.32
4972,Tablet,Accessories,Cust_189,UK,13-12-2023,3,310,0.08,863.0,855.60,4736.681682,Low,-7.40,-0.864890,74.40
4973,Laptop,Accessories,Cust_16,Canada,09-01-2022,2,647,0.21,1304.0,1022.26,4395.222126,Low,-281.74,-27.560503,271.74
4988,Monitor,Accessories,Cust_393,USA,06-08-2022,6,317,0.21,1388.0,1502.58,4741.873837,Medium,114.58,7.625551,399.42

In [246]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales,Region_Avg_Sales,Sales_Level,Profit,Profit_Margin,Total_Discount
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,4395.222126,High,3714.12,76.310426,996.88
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,4395.222126,High,5175.32,91.205995,2317.68
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,4736.681682,Low,231.40,23.506705,85.60
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,4395.222126,Low,206.48,24.479537,8.52
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,4395.222126,Very High,8559.75,93.114139,3064.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4395.222126,High,4779.28,98.313201,422.72
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4741.873837,High,4005.90,92.645528,646.10
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4644.249364,High,4439.32,87.693390,1345.68
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,4644.249364,Very High,6447.35,93.084381,1418.65
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,4736.681682,High,5217.00,82.704502,1292.00

In [247]:
from sqlalchemy import create_engine

engine= create_engine(
    "mssql+pyodbc://@TIRUPATI\\SQLEXPRESS/Retail?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&TrustServerCertificate=yes"
)
dataset.to_sql("Retail_Data", engine, if_exists="replace", index=False)

print("successfully data Loaded")

successfully data Loaded

In [248]:
dataset.shape

(4713, 15)

In [249]:
print(type(dataset))
print(dataset.columns)

<class 'pandas.core.frame.DataFrame'>
Index(['Product', 'Category', 'Customer', 'Region', 'Date', 'Quantity',
       'Unit Price', 'Discount', 'Cost', 'Sales', 'Region_Avg_Sales',
       'Sales_Level', 'Profit', 'Profit_Margin', 'Total_Discount'],
      dtype='object')